{{- if .Values.secret.enabled -}}
{{- $fullName := include "lookerbot.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "lookerbot.name" . }}
    helm.sh/chart: {{ include "lookerbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end }}
